<?php
    $form = $this->form;
    
    $form->prepare();
    echo $this->form()->openTag($form);
?>
<div class="form-group">
	<label for="city" class="col-sm-2 control-label"><?=$this->formLabel($form->get('city'))?></label>
	<div class="col-sm-10"><?=$this->formInput($form->get('city'))?></div>
</div>

<div class="form-group">
	<label for="country" class="col-sm-2 control-label"><?=$this->formLabel($form->get('country'))?></label>
	<div class="col-sm-10"><?=$this->formInput($form->get('country'))?></div>
</div>

<div class="form-group">
    <span class="col-sm-2"></span>
	<div class="col-sm-10"><?=$this->formInput($form->get('submit'))?></div>
</div>

<?=$this->form()->closeTag($form)?>

